name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.10"

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: |
          pytest app/test_main.py

  dockerize:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check Docker version
        run: docker --version

      - name: List files in parent directory
        run: ls -alh /home/runner/work/Fast_api_ml_app

      - name: Print current working directory
        run: pwd

      - name: Build Docker image with no cache
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/fastapi-ci-cd_ml:v1.0.0 -f /home/runner/work/Fast_api_ml_app/Dockerfile /home/runner/work/Fast_api_ml_app

      - name: List Docker images
        run: docker images

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-ci-cd_ml:v1.0.0
